FROM node:latest

# INSTALA PYTHON
RUN apt-get update || : && apt-get install python -y

# INSTALA BeautifulSoup
RUN pip install beautifulsoup4

# INICIA O SERVIDOR
CMD ["node", "./Server/index.js"]

# COPIA OS ARQUIVOS LOCAIS
COPY . .

# PORTA PADRAO DO APP
EXPOSE 5000